import type { ReactElement, ReactNode } from 'react'
import Head from 'next/head'

type LayoutProps = {
  children: ReactElement
}

export default function Layout({ children }: LayoutProps): ReactElement {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="bg-red-400">header</header>

      <main className="h-screen md:container md:mx-auto">{children}</main>

      <footer className="bg-gray-600">footer</footer>
    </>
  )
}
